export function nativeMenuLabels(t: (source: string) => string): Record<string, string> {
  return {
    "About rbxport": t("About rbxport"),
    "Settings…": t("Settings…"),
    "Check for Updates…": t("Check for Updates…"),
    "Hide rbxport": t("Hide rbxport"),
    "Hide Others": t("Hide Others"),
    "Quit rbxport": t("Quit rbxport"),
    File: t("File"),
    Import: t("Import"),
    "Import Folder…": t("Import Folder…"),
    "Import rekordbox xml…": t("Import rekordbox xml…"),
    "Import iTunes Library xml…": t("Import iTunes Library xml…"),
    "Export Collection in xml format…": t("Export Collection in xml format…"),
    "Display All Missing Files": t("Display All Missing Files"),
    "Close Window": t("Close Window"),
    Edit: t("Edit"),
    Undo: t("Undo"),
    Redo: t("Redo"),
    Cut: t("Cut"),
    Copy: t("Copy"),
    Paste: t("Paste"),
    "Select All": t("Select All"),
    View: t("View"),
    Layout: t("Layout"),
    "Media Player": t("Media Player"),
    "Display Tempo slider": t("Display Tempo slider"),
    "Information Window": t("Information Window"),
    "Sub-Browser Window": t("Sub-Browser Window"),
    "Full screen": t("Full screen"),
    "1 Player": t("1 Player"),
    "2 Players": t("2 Players"),
    "Simple Player": t("Simple Player"),
    "Full Browser": t("Full Browser"),
    Help: t("Help"),
    "Report bug…": t("Report bug…"),
  };
}
